version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api-legacy:
    container_name: api-legacy
    build:
      context: .
      dockerfile: ./apps/api-legacy/Dockerfile
    restart: always
    environment:
      - MONGO_URL=mongodb://legacy:password_legacy@db-legacy:27017
    ports:
      - 3001:3001
    networks:
      - app_network
  
  db-legacy:
    container_name: db-legacy
    image: mongo:4.0.4
    ports:
      - 27017:27017
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: legacy
      MONGO_INITDB_ROOT_PASSWORD: password_legacy
      MONGO_INITDB_DATABASE: legacy
      
  
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
